In [1]:
import tensorflow as tf
import numpy as np
tf.__version__

'2.16.1'

In [2]:
# 데이터는 constant, 모델에 들어가는 요소는 Variable로 구성
# 데이터는 immutable, 모델에 들어가는 요소는 mutable

t1 = tf.Variable([1,2,3])
t2 = tf.constant([1,2,3])

In [3]:
print(t1)
print(t2)
print('----')
print(type(t1))
print(type(t2))

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3])>
tf.Tensor([1 2 3], shape=(3,), dtype=int32)
----
<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [15]:
#### 리스트나 np 둘다 constant와 Variable로 만들수 있다

In [4]:
test_list = [1,2,3]
test_np = np.array([1,2,3])

t1 = tf.constant(test_list)
t2 = tf.constant(test_np)

In [5]:
print(t1)
print(t2)
print('----')
print(type(t1))
print(type(t2))

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)
----
<class 'tensorflow.python.framework.ops.EagerTensor'>
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [6]:
test_list = [1,2,3]
test_np = np.array([1,2,3])

t1 = tf.Variable(test_list)
t2 = tf.Variable(test_np)

In [7]:
print(t1)
print(t2)
print('----')
print(type(t1))
print(type(t2))

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3])>
<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3])>
----
<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>
<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>


#### constant의 경우 Variable로 변경하룻 있는데 Variable은 constant로 변경하지 못함    - 2.10.0은 되는듯????

In [38]:
test_list = [1,2,3]
test_np = np.array([1,2,3])
t1 = tf.constant(test_list)
t2 = tf.Variable(test_np)

In [40]:
print(t1)
print(t2)

print(type(t1))
print(type(t2))

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3])>
<class 'tensorflow.python.framework.ops.EagerTensor'>
<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>


In [43]:
t3 = tf.constant(t2)
t4 = tf.Variable(t1)

In [44]:
print(t3)
print(t4)

print(type(t3))
print(type(t4))

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3])>
<class 'tensorflow.python.framework.ops.EagerTensor'>
<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>


#### Variable변경방법

In [46]:
t1 = tf.convert_to_tensor(test_list)
t2 = tf.convert_to_tensor(test_np)
print(type(t1))
print(type(t2))

<class 'tensorflow.python.framework.ops.EagerTensor'>
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [47]:
t3 = tf.Variable(test_list)
t4 = tf.convert_to_tensor(t3)
print(type(t3))
print(type(t4))

<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>
<class 'tensorflow.python.framework.ops.EagerTensor'>


#### 연산을 하면 모든 경우 EagerTensor가 만들어진다

In [34]:
test_list1 = [10,20,30]
test_list2 = [1,2,3]

t1 = tf.constant(test_list1)
t2 = tf.constant(test_list2)

t3 = t1 + t2
t3

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([11, 22, 33])>

In [36]:
test_list1 = [10,20,30]
test_list2 = [1,2,3]

t1 = tf.constant(test_list1)
t2 = tf.Variable(test_list2)

t3 = t1 + t2
t3

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([11, 22, 33])>

In [37]:
test_list1 = [10,20,30]
test_list2 = [1,2,3]

t1 = tf.Variable(test_list1)
t2 = tf.Variable(test_list2)

t3 = t1 + t2
t3

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([11, 22, 33])>