In [4]:
import tensorflow as tf
import numpy as np

### 기본적인 연산

In [5]:
t1 = tf.constant([1,2,3])
t2 = tf.constant([10,20,30])

In [6]:
print(t1+t2)
print(t1-t2)
print(t1*t2)
print(t1/t2)
print(t1%t2)
print(t1//t2)

tf.Tensor([11 22 33], shape=(3,), dtype=int32)
tf.Tensor([ -9 -18 -27], shape=(3,), dtype=int32)
tf.Tensor([10 40 90], shape=(3,), dtype=int32)
tf.Tensor([0.1 0.1 0.1], shape=(3,), dtype=float64)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([0 0 0], shape=(3,), dtype=int32)


In [29]:
### 텐서의 연산규칙

In [20]:
t1 = tf.random.normal(shape=(3,4),mean=0,stddev=5)
t2 = tf.random.normal(shape=(1,4),mean=0,stddev=5)

In [22]:
t1 = tf.cast(t1,dtype=tf.int16)
t2 = tf.cast(t2,dtype=tf.int16)

In [24]:
t3 = t1+t2

In [26]:
print(t1.numpy(), '\n')
print(t2.numpy(), '\n')

print(t3.numpy(), '\n')

[[ 0  5 -4  5]
 [ 2  3  5 -8]
 [ 4 -1  0  0]] 

[[-7 -1  8  9]] 

[[-7  4  4 14]
 [-5  2 13  1]
 [-3 -2  8  9]] 



In [28]:
t1 = tf.random.normal(shape=(1,4),mean=0,stddev=5)
t2 = tf.random.normal(shape=(4,1),mean=0,stddev=5)

t1 = tf.cast(t1,dtype=tf.int16)
t2 = tf.cast(t2,dtype=tf.int16)

print(t1.numpy(), '\n')
print(t2.numpy(), '\n')

print(t3.numpy(), '\n')

[[ 4  2  2 -3]] 

[[-7]
 [ 0]
 [-7]
 [ 0]] 

[[-7  4  4 14]
 [-5  2 13  1]
 [-3 -2  8  9]] 



In [30]:
### 다양한 tf연산방법들

In [ ]:
tf.reduce_sum
tf.reduce_prod

tf.reduce_min
tf.reduce_max

tf.reduce_mean
tf.reduce_std
tf.reduce_variance

tf.reduce_all
tf.reduce_any

In [34]:
t1 = tf.random.normal(shape=(3,4),mean=0,stddev=5)
t1 = tf.cast(t1, dtype=tf.int16)
print(t1.numpy())

t2 = tf.reduce_sum(t1)
print(t2.numpy())

[[ 0  4  0  2]
 [ 2  8  6  3]
 [ 0  3 -3  5]]
30


In [35]:
## axis를 설정해서 행, 열만 더할수도 있음
t1 = tf.random.normal(shape=(3,4),mean=0,stddev=5)
t1 = tf.cast(t1, dtype=tf.int16)
print(t1.numpy())

t2 = tf.reduce_sum(t1, axis=0)
print(t2.numpy())

[[  2  -2  -4   0]
 [  4   2  -4   2]
 [  0   0  -3 -10]]
[  6   0 -11  -8]


In [37]:
## 이미지 파일로 한다면
t1 = tf.random.normal(shape=(128,128,3),mean=0,stddev=5)
t1 = tf.cast(t1, dtype=tf.int16)
print(t1.shape)

t2 = tf.reduce_sum(t1, axis=2)
print(t2.shape)

(128, 128, 3)
(128, 128)
